/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:674502:
  println("ADDED COFEE");
  numClicks ++;
} //_CODE_:button1:674502:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:733988:
  println("ADDED MILK");
  numClicks ++ ;
} //_CODE_:button2:733988:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:881086:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
  numClicks ++ ; 
} //_CODE_:button3:881086:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 1060, 88, 140, 90);
  button1.setText(" ADD COFFEE");
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 1061, 226, 140, 100);
  button2.setText("ADD MILK");
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(this, 1066, 369, 140, 100);
  button3.setText("ADD ESPRESSO");
  button3.addEventHandler(this, "button3_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GButton button2; 
GButton button3; 
